RedditClone/config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :posts do
    resources :comments, only: [:new, :create]
  end
  resources :comments, only: [:show]
  resources :subs
  resources :posts, except: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

RedditClone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :bigint(8)        not null, primary key
#  title       :string           not null
#  description :string           not null
#  user_id     :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, :description, presence: true

  belongs_to :moderator,
  foreign_key: :user_id,
  class_name: :User

  has_many :posts,
    through: :post_subs,
    source: :post

  has_many :post_subs
end

RedditClone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_login

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.user_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find_by(id: params[:id])
  end

  def update
    @sub = Sub.find_by(id: params[:id])
    if current_user.id == @sub.moderator.id && @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find_by(id: params[:id])
  end

  def destroy
  end

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

RedditClone/app/helpers/subs_helper.rb
module SubsHelper
end

RedditClone/app/views/subs/create.html.erb
<h1>Subs#create</h1>
<p>Find me in app/views/subs/create.html.erb</p>

RedditClone/app/views/subs/destroy.html.erb
<h1>Subs#destroy</h1>
<p>Find me in app/views/subs/destroy.html.erb</p>

RedditClone/app/views/subs/edit.html.erb
<h1>Edit Sub</h1>
<form action="<%= subs_url %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="PATCH">

  <label>Title:
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>

  <label>Description:
    <textarea name="sub[description]" rows="8" cols="40"><%= @sub.description %></textarea>
  </label>

  <input type="submit" value="Update Sub">
</form>

RedditClone/app/views/subs/index.html.erb
<div class="sub-div">

<h1>All Subs</h1>

<ul>
  <% @subs.each do |sub| %>
    <li><a href="<%= sub_url(sub) %>"><%= sub.title %></a></li>
  <% end %>
</ul>


</div>

RedditClone/app/views/subs/new.html.erb
<h1>Create New Sub</h1>
<form action="<%= subs_url %>" method="post">
  <%= auth_token %>

  <label>Title:
    <input type="text" name="sub[title]" placeholder="title">
  </label>

  <label>Description:
    <textarea name="sub[description]" rows="8" cols="40"></textarea>
  </label>

  <input type="submit" value="Create New Sub">
</form>

RedditClone/app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>
<p><%= @sub.description %></p>
<br>
<a href="<%= edit_sub_url(@sub) %>">Edit</a>
<br>
<a href="<%= subs_url %>">Return to Subs</a>

RedditClone/app/views/subs/update.html.erb
<h1>Subs#update</h1>
<p>Find me in app/views/subs/update.html.erb</p>