RedditClone/config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :posts do
    resources :comments, only: [:new, :create]
  end
  resources :comments, only: [:show]
  resources :subs
  resources :posts, except: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

RedditClone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email, :password_digest, :session_token, presence: true, uniqueness:true
  validates :password, length: {minimum:6, allow_nil: true}

  attr_reader :password

  after_initialize :ensure_session_token

  def self.validate_credentials(email, password)
    user = User.find_by(email: email)

    user && user.is_password?(password) ? user : nil
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  has_many :subs,
  foreign_key: :user_id,
  class_name: :Sub

  has_many :posts,
    foreign_key: :user_id,
    class_name: :Post

  has_many :comments,
    foreign_key: :user_id,
    class_name: :Comment
end

RedditClone/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)

    if @user.save
      session[:session_token] = @user.session_token
      redirect_to new_user_url
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

RedditClone/app/helpers/users_helper.rb
module UsersHelper
end

RedditClone/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

RedditClone/app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

RedditClone/app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

RedditClone/app/views/users/new.html.erb
<h1>Sign Up</h1>
<form action="<%= users_url %>" method="post">
  <%= auth_token %>

  <label>
    Email:
  <input type="text" name="user[email]" placeholder="email">
  </label>

  <label>
  Password:
  <input type="password" name="user[password]" placeholder="password">
  </label>

  <input type="submit" value="Sign Up">
</form>

RedditClone/app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>