RedditClone/config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :posts do
    resources :comments, only: [:new, :create]
  end
  resources :comments, only: [:show]
  resources :subs
  resources :posts, except: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

RedditClone/app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id                :bigint(8)        not null, primary key
#  content           :string           not null
#  user_id           :integer          not null
#  post_id           :integer          not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  parent_comment_id :integer
#

class Comment < ApplicationRecord
  validates_presence_of :content

  belongs_to :parent_comment,
    foreign_key: :parent_comment_id,
    class_name: :Comment,
    optional: true

  has_many :child_comments,
    foreign_key: :parent_comment_id,
    class_name: :Comment

  belongs_to :author,
    foreign_key: :user_id,
    class_name: :User

  belongs_to :post,
    optional: true
end

RedditClone/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  helper_method :list_all_children
  before_action :require_login

  def show
    @comment = Comment.find_by(id: params[:id])
  end

  def new
    @comment = Comment.new(post_id: params[:post_id])
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.post_id = params[:post_id]
    @comment.user_id = current_user.id
    @comment.parent_comment_id = params[:parent_comment_id]

    if @comment.save
      redirect_to post_url(@comment.post_id)
    else
      flash[:errors] = @comment.errors.full_messages
      render :new
    end
  end



  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

RedditClone/app/views/comments/new.html.erb
<h1>New Comment!</h1>

<form action="<%= post_comments_url(@comment.post_id) %>" method="post">
  <%= auth_token %>
  <label>Body
    <textarea name="comment[content]" rows="8" cols="40"></textarea>
  </label>
  <br>
  <input type="submit" value="Submit">
</form>

RedditClone/app/views/comments/show.html.erb
<h2><%= @comment.content %></h2>

<form action="<%= post_comments_url(@comment.post_id) %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="parent_comment_id" value="<%= @comment.id %>">
  <label>Body
    <textarea name="comment[content]" rows="8" cols="40"></textarea>
  </label>
  <br>
  <input type="submit" value="Submit">
</form>