RedditClone/config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :posts do
    resources :comments, only: [:new, :create]
  end
  resources :comments, only: [:show]
  resources :subs
  resources :posts, except: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

RedditClone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  url        :string           not null
#  content    :string           not null
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates_presence_of :url, :title, :content
  validates :subs, presence: { message: 'Must have at least one sub'}

  def top_level_comments
    comments.where(:parent_comment_id => nil).includes(:author).includes(:child_comments)
  end

  belongs_to :author,
    foreign_key: :user_id,
    class_name: :User

  has_many :post_subs, inverse_of: :post

  has_many :subs,
    through: :post_subs,
    source: :sub

  has_many :comments
end

RedditClone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  helper_method :list_all_children
  def new
    @subs = Sub.all
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @subs = Sub.all
    @post = Post.find_by(id: params[:id])
  end

  def update
    @post = current_user.posts.find_by(id: params[:id])
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    redirect_to subs_url
  end

  def list_all_children(parent_comment)
    return "" if parent_comment.empty?

    result = "<ul>".html_safe
      parent_comment.each do |parent|
        result += "<li><a href=\"#{comment_url(parent)}\">#{parent.content}</a></li>".html_safe
        result += list_all_children(parent.child_comments)
      end
    result += "</ul>".html_safe
  end

  def post_params
    params.require(:post).permit(:title, :url, :content, :sub_ids => [])
  end
end

RedditClone/app/helpers/posts_helper.rb
module PostsHelper
end

RedditClone/app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

RedditClone/app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

RedditClone/app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<form action="<%= posts_url(@post) %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="PATCH">

  <label>Title:
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>
<br>
  <label>URL:
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label>
<br>
  <label>Content:
    <textarea name="post[content]" rows="8" cols="40"><%= @post.content %></textarea>
  </label>

<h2>Associated Subs</h2>
<ul>
<% @subs.each do |sub| %>
  <li><input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>" checked>
  <%= sub.title %></li>
  <br>
<% end %>
</ul>
  <input type="submit" value="Update Post">
</form>

RedditClone/app/views/posts/new.html.erb
<h1>Create New Post</h1>
<form action="<%= posts_url(@post) %>" method="post">
  <%= auth_token %>

  <label>Title:
    <input type="text" name="post[title]" >
  </label>
<br>
  <label>URL:
    <input type="text" name="post[url]" >
  </label>
<br>
  <label>Content:
    <textarea name="post[content]" rows="8" cols="40"></textarea>
  </label>

<h2>Associated Subs</h2>
<ul>
<% @subs.each do |sub| %>
  <li><input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>">
  <%= sub.title %></li>
  <br>
<% end %>
</ul>
  <input type="submit" value="Create Post">
</form>

RedditClone/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<div class="content" style="border: 1px solid black; margin: 10px; padding: 8px;">
  <p>Content:</p>
  <p><%= @post.content %></p>
</div>

<button type="button" name="upvote">Upvote</button>
<button type="button" name="downvote">Downvote</button>

<form action="<%= post_url(@post) %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="DELETE">
  <input type="submit" value="Delete Post" style="background-color: red">
</form>

<h3>Subs</h3>
  <ul>
    <% @post.subs.each do |sub| %>
      <li><a href="<%= sub_url(sub) %>"><%= sub.title %></a></li>
    <% end %>
  </ul>

<h2>Comments</h2>
<a href="<%= new_post_comment_url(@post.id) %>">Add Comment</a>
<%= list_all_children(@post.top_level_comments) %>

<p>Find me in app/views/posts/show.html.erb</p>

RedditClone/app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>